import type {
  Reservation,
  Inquiry,
  VoiceLog,
  Knowledge,
  Room,
  Staff,
} from "./types";

// 「現在日時」を固定してデモの再現性を担保
export const NOW = new Date("2026-06-04T14:30:00+09:00");
export const HOTEL_NAME = "グランドベイ・ホテル横浜";

// ---- 予約 ----
export const reservations: Reservation[] = [
  {
    id: "RSV-1042",
    guestName: "山田 太郎",
    guestNameKana: "ヤマダ タロウ",
    phone: "090-1234-5678",
    email: "yamada.taro@example.com",
    checkIn: "2026-06-10",
    checkOut: "2026-06-12",
    roomType: "デラックスツイン",
    roomNumber: "302",
    guests: 2,
    adults: 2,
    children: 0,
    price: 28000,
    payment: "credit",
    status: "confirmed",
    channel: "phone",
    staff: "鈴木 美咲",
    note: "高層階希望。記念日のため夕食時にメッセージカード手配。",
    createdAt: "2026-06-01T10:12:00+09:00",
  },
  {
    id: "RSV-1043",
    guestName: "佐藤 花子",
    guestNameKana: "サトウ ハナコ",
    phone: "080-2222-3333",
    email: "hanako.sato@example.com",
    checkIn: "2026-06-04",
    checkOut: "2026-06-06",
    roomType: "スタンダードダブル",
    roomNumber: "501",
    guests: 2,
    adults: 2,
    children: 0,
    price: 19800,
    payment: "onsite",
    status: "checkedIn",
    channel: "web",
    staff: "田中 健",
    createdAt: "2026-05-28T09:40:00+09:00",
  },
  {
    id: "RSV-1044",
    guestName: "高橋 一郎",
    phone: "070-4444-5555",
    email: "ichiro.t@example.com",
    checkIn: "2026-06-04",
    checkOut: "2026-06-05",
    roomType: "シングル",
    roomNumber: "210",
    guests: 1,
    adults: 1,
    children: 0,
    price: 9800,
    payment: "prepaid",
    status: "checkedIn",
    channel: "agency",
    staff: "鈴木 美咲",
    note: "JTB経由。late check-in 22時予定。",
    createdAt: "2026-05-30T15:05:00+09:00",
  },
  {
    id: "RSV-1045",
    guestName: "渡辺 由美",
    phone: "090-6666-7777",
    email: "yumi.w@example.com",
    checkIn: "2026-06-05",
    checkOut: "2026-06-08",
    roomType: "ファミリースイート",
    roomNumber: "705",
    guests: 4,
    adults: 2,
    children: 2,
    price: 62000,
    payment: "credit",
    status: "confirmed",
    channel: "phone",
    staff: "田中 健",
    note: "ベビーベッド1台、子ども用アメニティ希望。",
    createdAt: "2026-06-02T11:30:00+09:00",
  },
  {
    id: "RSV-1046",
    guestName: "中村 翔",
    phone: "080-8888-9999",
    email: "sho.n@example.com",
    checkIn: "2026-06-04",
    checkOut: "2026-06-04",
    roomType: "デイユース",
    roomNumber: "115",
    guests: 1,
    adults: 1,
    children: 0,
    price: 4500,
    payment: "cash",
    status: "tentative",
    channel: "walkIn",
    staff: "鈴木 美咲",
    createdAt: "2026-06-04T08:55:00+09:00",
  },
  {
    id: "RSV-1047",
    guestName: "小林 さくら",
    phone: "090-1010-2020",
    email: "sakura.k@example.com",
    checkIn: "2026-06-02",
    checkOut: "2026-06-04",
    roomType: "スタンダードツイン",
    roomNumber: "408",
    guests: 2,
    adults: 2,
    children: 0,
    price: 22000,
    payment: "credit",
    status: "checkedOut",
    channel: "web",
    staff: "田中 健",
    createdAt: "2026-05-25T19:20:00+09:00",
  },
  {
    id: "RSV-1048",
    guestName: "伊藤 大輔",
    phone: "070-3030-4040",
    email: "daisuke.i@example.com",
    checkIn: "2026-06-11",
    checkOut: "2026-06-13",
    roomType: "デラックスキング",
    roomNumber: "601",
    guests: 2,
    adults: 2,
    children: 0,
    price: 34000,
    payment: "invoice",
    status: "confirmed",
    channel: "agency",
    staff: "鈴木 美咲",
    note: "法人契約（株式会社オーシャン）。請求書払い。",
    createdAt: "2026-06-03T13:10:00+09:00",
  },
  {
    id: "RSV-1049",
    guestName: "松本 愛",
    phone: "080-5050-6060",
    email: "ai.m@example.com",
    checkIn: "2026-06-04",
    checkOut: "2026-06-07",
    roomType: "スタンダードダブル",
    roomNumber: "503",
    guests: 2,
    adults: 2,
    children: 0,
    price: 29700,
    payment: "credit",
    status: "confirmed",
    channel: "phone",
    staff: "田中 健",
    createdAt: "2026-06-03T17:42:00+09:00",
  },
  {
    id: "RSV-1050",
    guestName: "木村 健太",
    phone: "090-7070-8080",
    email: "kenta.k@example.com",
    checkIn: "2026-06-06",
    checkOut: "2026-06-09",
    roomType: "デラックスツイン",
    roomNumber: "304",
    guests: 3,
    adults: 2,
    children: 1,
    price: 48000,
    payment: "credit",
    status: "tentative",
    channel: "other",
    staff: "鈴木 美咲",
    note: "公式LINEから問い合わせ → 仮予約。支払い方法未確定。",
    createdAt: "2026-06-04T12:01:00+09:00",
  },
];

// ---- 問い合わせ ----
export const inquiries: Inquiry[] = [
  {
    id: "INQ-2201",
    guestName: "佐藤 花子",
    roomNumber: "501",
    content: "枕をもう一つ追加してほしいです。少し高めのものがあれば嬉しいです。",
    category: "amenity",
    status: "open",
    priority: "medium",
    createdAt: "2026-06-04T13:55:00+09:00",
    aiHandled: true,
    needsHuman: true,
    aiAnswer:
      "かしこまりました。追加の枕（高め）をお持ちいたします。ハウスキーピングへ手配いたしますので少々お待ちください。",
    memo: "高め枕の在庫を清掃カートで確認のこと。",
  },
  {
    id: "INQ-2202",
    guestName: "高橋 一郎",
    roomNumber: "210",
    content: "Wi-Fiのパスワードを教えてください。",
    category: "wifi",
    status: "resolved",
    priority: "low",
    createdAt: "2026-06-04T12:20:00+09:00",
    assignee: "AI コンシェルジュ",
    aiHandled: true,
    needsHuman: false,
    aiAnswer:
      "Wi-Fi名は Hotel-Free-WiFi、パスワードはお部屋の案内カードに記載しております。ご不明な場合はフロントまでご連絡ください。",
  },
  {
    id: "INQ-2203",
    guestName: "渡辺 由美",
    roomNumber: "705",
    content: "上の階から大きな物音がして眠れません。確認してもらえますか？",
    category: "trouble",
    status: "inProgress",
    priority: "high",
    createdAt: "2026-06-04T14:05:00+09:00",
    assignee: "田中 健",
    aiHandled: true,
    needsHuman: true,
    aiAnswer:
      "ご不便をおかけし申し訳ございません。担当スタッフが状況を確認し、ご対応いたします。",
    memo: "805号室へ状況確認に向かう。",
  },
  {
    id: "INQ-2204",
    guestName: "松本 愛",
    roomNumber: "503",
    content: "エアコンが効かず部屋が暑いです。至急見てほしいです。",
    category: "trouble",
    status: "needsStaff",
    priority: "urgent",
    createdAt: "2026-06-04T14:18:00+09:00",
    assignee: "メンテナンス",
    aiHandled: true,
    needsHuman: true,
    aiAnswer:
      "大変申し訳ございません。設備担当がすぐにお部屋へ伺います。必要に応じてお部屋の移動もご案内いたします。",
    memo: "メンテナンス佐々木へエスカレーション済み。代替室 505 を確保。",
  },
  {
    id: "INQ-2205",
    guestName: "高橋 一郎",
    roomNumber: "210",
    content: "チェックアウトの時間は何時までですか？",
    category: "checkInOut",
    status: "resolved",
    priority: "low",
    createdAt: "2026-06-04T11:02:00+09:00",
    assignee: "AI コンシェルジュ",
    aiHandled: true,
    needsHuman: false,
    aiAnswer: "チェックアウトは午前11時までとなっております。",
  },
  {
    id: "INQ-2206",
    guestName: "佐藤 花子",
    roomNumber: "501",
    content: "近くにコンビニはありますか？",
    category: "nearby",
    status: "resolved",
    priority: "low",
    createdAt: "2026-06-04T10:40:00+09:00",
    assignee: "AI コンシェルジュ",
    aiHandled: true,
    needsHuman: false,
    aiAnswer:
      "ホテルを出て右手に徒歩2分のところにコンビニがございます。24時間営業です。",
  },
  {
    id: "INQ-2207",
    guestName: "中村 翔",
    roomNumber: "115",
    content: "ルームサービスで軽食を頼みたいのですが。",
    category: "roomService",
    status: "open",
    priority: "medium",
    createdAt: "2026-06-04T14:22:00+09:00",
    aiHandled: false,
    needsHuman: true,
  },
];

// ---- 音声 AI ログ ----
export const voiceLogs: VoiceLog[] = [
  {
    id: "VL-3301",
    guestName: "山田 太郎",
    roomNumber: "402",
    sttText: "電気のスイッチはどこですか？",
    category: "facility",
    aiAnswer:
      "電気のスイッチは、お部屋の入口横とベッドサイドにございます。ベッドサイドのパネルで室内照明をまとめて操作いただけます。",
    ttsStatus: "played",
    status: "completed",
    needsStaff: false,
    startedAt: "2026-06-04T13:40:00+09:00",
    endedAt: "2026-06-04T13:40:38+09:00",
    durationSec: 38,
    transcript: [
      { role: "guest", text: "電気のスイッチはどこですか？", at: "13:40:05" },
      {
        role: "ai",
        text: "電気のスイッチは、お部屋の入口横とベッドサイドにございます。",
        at: "13:40:12",
      },
    ],
  },
  {
    id: "VL-3302",
    guestName: "佐藤 花子",
    roomNumber: "501",
    sttText: "朝食は何時から何時までですか？会場はどこですか？",
    category: "breakfast",
    aiAnswer:
      "朝食は午前6時30分から10時まで、2階のレストラン「マリーナ」でご提供しております。お部屋番号をお伝えください。",
    ttsStatus: "played",
    status: "completed",
    needsStaff: false,
    startedAt: "2026-06-04T07:10:00+09:00",
    endedAt: "2026-06-04T07:10:45+09:00",
    durationSec: 45,
    transcript: [
      { role: "guest", text: "朝食は何時からですか？", at: "07:10:03" },
      {
        role: "ai",
        text: "朝食は午前6時30分から10時まで、2階のレストランでご提供しております。",
        at: "07:10:10",
      },
    ],
  },
  {
    id: "VL-3303",
    guestName: "松本 愛",
    roomNumber: "503",
    sttText: "エアコンが全然効かないんですけど、すぐ来てもらえますか？",
    category: "trouble",
    aiAnswer:
      "ご不便をおかけし申し訳ございません。設備担当へ連絡し、すぐにお部屋へ伺うよう手配いたします。",
    ttsStatus: "played",
    status: "escalated",
    needsStaff: true,
    startedAt: "2026-06-04T14:17:00+09:00",
    endedAt: "2026-06-04T14:18:10+09:00",
    durationSec: 70,
    escalationReason: "設備トラブル（空調不良）のため人間対応が必要と判断。",
    transcript: [
      {
        role: "guest",
        text: "エアコンが全然効かないんですけど",
        at: "14:17:05",
      },
      {
        role: "ai",
        text: "申し訳ございません。設備担当へ連絡いたします。",
        at: "14:17:14",
      },
      {
        role: "staff",
        text: "（メンテナンス佐々木へ転送）",
        at: "14:18:02",
      },
    ],
  },
  {
    id: "VL-3304",
    guestName: "中村 翔",
    roomNumber: "115",
    sttText: "駐車場はどこに停めればいいですか？",
    category: "parking",
    aiAnswer:
      "駐車場は地下1階にございます。エレベーター横の入口からお入りください。1泊1,500円で承っております。",
    ttsStatus: "pending",
    status: "transcribing",
    needsStaff: false,
    startedAt: "2026-06-04T14:28:00+09:00",
    durationSec: 12,
    transcript: [
      { role: "guest", text: "駐車場はどこに…", at: "14:28:04" },
    ],
  },
];

// ---- ナレッジ ----
export const knowledgeBase: Knowledge[] = [
  {
    id: "KB-01",
    title: "電気のスイッチはどこですか？",
    category: "facility",
    phrases: ["電気どこ", "照明のつけ方", "スイッチが見つからない", "ライトの操作"],
    answer:
      "お部屋の入口横、ベッドサイド、デスク横にスイッチがございます。ベッドサイドのパネルでは、室内照明をまとめて操作できます。",
    voiceAnswer:
      "電気のスイッチは、お部屋の入口横とベッドサイドにございます。",
    handling: "AI 音声案内で完結。再質問が続く場合のみフロント対応。",
    needsStaff: false,
    priority: "low",
    published: true,
    useForAi: true,
    updatedAt: "2026-05-20",
    author: "鈴木 美咲",
  },
  {
    id: "KB-02",
    title: "Wi-Fiのパスワードを教えてください",
    category: "wifi",
    phrases: ["wifi", "ワイファイ", "ネット接続", "インターネット", "パスワード"],
    answer:
      "Wi-Fi名は Hotel-Free-WiFi、パスワードはフロントでお渡しした案内カードに記載されています。接続できない場合はフロントまでご連絡ください。",
    voiceAnswer:
      "Wi-Fi名はHotel-Free-WiFi、パスワードはお部屋の案内カードに記載しております。",
    handling: "AI 音声案内で完結。",
    needsStaff: false,
    priority: "low",
    published: true,
    useForAi: true,
    updatedAt: "2026-05-22",
    author: "田中 健",
  },
  {
    id: "KB-03",
    title: "チェックアウトの時間は？",
    category: "checkInOut",
    phrases: ["チェックアウト", "何時まで", "退室時間", "延長できる"],
    answer:
      "チェックアウトは午前11時までです。レイトチェックアウトは1時間あたり1,000円で承ります（空室状況により最長14時まで）。",
    voiceAnswer: "チェックアウトは午前11時までとなっております。",
    handling: "延長希望の場合はフロントで空室確認のうえ対応。",
    needsStaff: false,
    priority: "low",
    published: true,
    useForAi: true,
    updatedAt: "2026-05-18",
    author: "鈴木 美咲",
  },
  {
    id: "KB-04",
    title: "朝食の時間と会場は？",
    category: "breakfast",
    phrases: ["朝食", "朝ごはん", "ブレックファスト", "レストラン場所"],
    answer:
      "朝食は午前6時30分から10時まで、2階レストラン「マリーナ」でビュッフェ形式にてご提供しております。お部屋番号をお伝えください。",
    voiceAnswer:
      "朝食は朝6時半から10時まで、2階のレストランでご利用いただけます。",
    handling: "AI 音声案内で完結。",
    needsStaff: false,
    priority: "low",
    published: true,
    useForAi: true,
    updatedAt: "2026-05-25",
    author: "田中 健",
  },
  {
    id: "KB-05",
    title: "エアコン・空調の不調",
    category: "trouble",
    phrases: ["エアコン効かない", "暑い", "寒い", "空調", "冷房", "暖房"],
    answer:
      "ご不便をおかけし申し訳ございません。リモコンの設定をご確認のうえ、改善しない場合は設備担当が確認に伺います。状況により代替のお部屋をご案内します。",
    voiceAnswer:
      "申し訳ございません。設備担当がすぐにお部屋へ伺います。",
    handling: "必ず人間（メンテナンス）へエスカレーション。",
    needsStaff: true,
    priority: "high",
    published: true,
    useForAi: true,
    updatedAt: "2026-06-01",
    author: "鈴木 美咲",
  },
  {
    id: "KB-06",
    title: "駐車場の場所と料金",
    category: "parking",
    phrases: ["駐車場", "車", "パーキング", "停める場所"],
    answer:
      "駐車場は地下1階です。エレベーター横の入口よりお入りください。料金は1泊1,500円（先着順）です。満車の場合は近隣提携駐車場をご案内します。",
    voiceAnswer:
      "駐車場は地下1階、1泊1,500円でご利用いただけます。",
    handling: "AI 音声案内で完結。満車時はフロント対応。",
    needsStaff: false,
    priority: "medium",
    published: true,
    useForAi: true,
    updatedAt: "2026-05-30",
    author: "田中 健",
  },
  {
    id: "KB-07",
    title: "周辺のコンビニ・飲食店",
    category: "nearby",
    phrases: ["コンビニ", "近くのお店", "飲食店", "周辺"],
    answer:
      "ホテルを出て右手・徒歩2分にコンビニ（24時間）がございます。徒歩5分圏内に飲食店も多数ございますので、マップをお渡しします。",
    voiceAnswer:
      "コンビニはホテルを出て右手、徒歩2分のところにございます。",
    handling: "AI 音声案内で完結。",
    needsStaff: false,
    priority: "low",
    published: false,
    useForAi: false,
    updatedAt: "2026-05-15",
    author: "鈴木 美咲",
  },
];

// ---- 客室 ----
export const rooms: Room[] = [
  { id: "R-115", number: "115", type: "デイユース", capacity: 1, status: "vacant", price: 4500, amenitiesOk: true },
  { id: "R-210", number: "210", type: "シングル", capacity: 1, guestName: "高橋 一郎", status: "occupied", price: 9800, amenitiesOk: true },
  { id: "R-302", number: "302", type: "デラックスツイン", capacity: 2, status: "cleaned", price: 14000, amenitiesOk: true },
  { id: "R-304", number: "304", type: "デラックスツイン", capacity: 3, status: "cleaning", price: 16000, amenitiesOk: false, maintenanceNote: "リネン補充待ち" },
  { id: "R-408", number: "408", type: "スタンダードツイン", capacity: 2, status: "cleaning", price: 11000, amenitiesOk: false },
  { id: "R-501", number: "501", type: "スタンダードダブル", capacity: 2, guestName: "佐藤 花子", status: "occupied", price: 9900, amenitiesOk: true },
  { id: "R-503", number: "503", type: "スタンダードダブル", capacity: 2, guestName: "松本 愛", status: "maintenance", price: 9900, amenitiesOk: false, maintenanceNote: "空調不良。設備担当対応中。" },
  { id: "R-601", number: "601", type: "デラックスキング", capacity: 2, status: "vacant", price: 17000, amenitiesOk: true },
  { id: "R-705", number: "705", type: "ファミリースイート", capacity: 4, guestName: "渡辺 由美", status: "occupied", price: 20600, amenitiesOk: true },
  { id: "R-808", number: "808", type: "コーナースイート", capacity: 3, status: "outOfService", price: 24000, amenitiesOk: false, maintenanceNote: "内装リニューアル工事中（〜6/20）" },
];

// ---- スタッフ ----
export const staffList: Staff[] = [
  { id: "S-01", name: "鈴木 美咲", role: "front", email: "suzuki@grandbay.example", phone: "045-111-0001", openInquiries: 2, workStatus: "working" },
  { id: "S-02", name: "田中 健", role: "front", email: "tanaka@grandbay.example", phone: "045-111-0002", openInquiries: 1, workStatus: "working" },
  { id: "S-03", name: "佐々木 修", role: "maintenance", email: "sasaki@grandbay.example", phone: "045-111-0003", openInquiries: 1, workStatus: "working" },
  { id: "S-04", name: "山口 久美", role: "cleaning", email: "yamaguchi@grandbay.example", phone: "045-111-0004", openInquiries: 0, workStatus: "break" },
  { id: "S-05", name: "井上 大地", role: "cleaning", email: "inoue@grandbay.example", phone: "045-111-0005", openInquiries: 0, workStatus: "working" },
  { id: "S-06", name: "森 麻衣", role: "admin", email: "mori@grandbay.example", phone: "045-111-0000", openInquiries: 0, workStatus: "off" },
];

// 現在ログイン中スタッフ（ヘッダー表示用）
export const currentStaff = staffList[0];

// ---- ダッシュボード集計（モック） ----
export const dashboardStats = {
  checkInsToday: 4,
  checkOutsToday: 3,
  guestsStaying: 9,
  vacantRooms: 8,
  openInquiries: 3,
  phoneReservationsToday: 5,
  urgentInquiries: 1,
  aiStatus: "online" as "online" | "offline",
  aiHandledToday: 27,
  aiResolutionRate: 0.82,
};
